// Generated by CoffeeScript 1.10.0
var Ractive, RactiveCompiler, sysPath, umd;

Ractive = require('ractive');

umd = require('umd-wrapper');

sysPath = require('path');

module.exports = RactiveCompiler = (function() {
  RactiveCompiler.prototype.brunchPlugin = true;

  RactiveCompiler.prototype.type = 'template';

  RactiveCompiler.prototype.extension = 'rac';

  RactiveCompiler.prototype.pattern = /\.(?:rac|ractive)$/;

  function RactiveCompiler(config) {
    this.config = config;
    null;
  }

  RactiveCompiler.prototype.compile = function(data, path, callback) {
    var err, error, error1, result;
    try {
      return result = umd(JSON.stringify(Ractive.parse(data)));
    } catch (error1) {
      err = error1;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  return RactiveCompiler;

})();
